/* AUTO-GENERATED by flight_policy.py via m2cgen.
 * Inputs (5 doubles, in order):
 *   input[0] = mission_day
 *   input[1] = f107_now
 *   input[2] = f107_slope_30d
 *   input[3] = altitude_km
 *   input[4] = days_since_eom
 * Output: 2-element array [WAIT_score, DEPLOY_score].
 * IC fires burn wire if DEPLOY_score > WAIT_score.
 */

#include <string.h>
void orion_deploy_policy(double * input, double * output) {
    double var0[2];
    if (input[4] <= -19.0) {
        memcpy(var0, (double[]){1.0, 0.0}, 2 * sizeof(double));
    } else {
        if (input[4] <= 23.0) {
            memcpy(var0, (double[]){0.0, 1.0}, 2 * sizeof(double));
        } else {
            if (input[3] <= 590.0) {
                memcpy(var0, (double[]){1.0, 0.0}, 2 * sizeof(double));
            } else {
                memcpy(var0, (double[]){1.0, 0.0}, 2 * sizeof(double));
            }
        }
    }
    memcpy(output, var0, 2 * sizeof(double));
}
